import{b,A as w,S as l,N as f,a as h,E as y,c as v,K as E,i as g}from"./assets/vendor-R6FCRirK.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&n(i)}).observe(document,{childList:!0,subtree:!0});function o(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function n(e){if(e.ep)return;e.ep=!0;const r=o(e);fetch(e.href,r)}})();const L=document.querySelector("#covers"),u=document.querySelector(".covers-background"),c=document.querySelector(".covers-wrapper");function S(t){t.forEach(s=>{s.isIntersecting?(u.classList.add("animated"),c.classList.add("animated")):(u.classList.remove("animated"),c.classList.remove("animated"))})}const C=new IntersectionObserver(S,{root:null,threshold:0});C.observe(L);function k(t){if(t.preventDefault(),t.target.nodeName!=="IMG")return;const s=t.target.currentSrc,o=b.create(`<img
      src="${s}"
      alt="${t.target.alt}"
      class="covers-full-image"
    />`,{onShow:e=>{window.addEventListener("keydown",n)},onClose:e=>{window.removeEventListener("keydown",n)}});o.show();function n(e){e.code==="Escape"&&o.close()}}c.addEventListener("click",k);const q=document.querySelector(".about-accordion-container");new w(q,{openOnInit:[0],showMultiple:!1,duration:500,elementClass:"about-ac",panelClass:"about-ac-panel",triggerClass:"about-ac-btn"});new l(".about-skills",{navigation:{nextEl:".about-swiper-btn"},keyboard:{enabled:!0,onlyInViewport:!0,pageUpDown:!0},mousewheel:{invert:!0},grabCursor:!0,touchEventsTarget:"wrapper",slideClass:"about-skills-item",slideActiveClass:"about-skills-item-accent",wrapperClass:"about-skills-list",slidesPerView:2,loopedSlides:2,spaceBetween:1,loop:!0,breakpoints:{768:{slidesPerView:3},1440:{slidesPerView:5,loopedSlides:5,spaceBetween:25}}});new l(".projects-swiper-container",{modules:[f,h,y],direction:"horizontal",loop:!1,slidesPerView:1,spaceBetween:10,mousewheel:!0,effect:"cards",grabCursor:!0,keyboard:{enabled:!0,onlyInViewport:!0},navigation:{nextEl:".projects-swiper-btn-next",prevEl:".projects-swiper-btn-prev",disabledClass:"projects-swiper-btn-disabled"}});document.querySelector(".accordion-container");new w(".accordion",{openOnInit:[],showMultiple:!1,duration:800,easing:"ease-in-out",triggerClass:"btn-svg-opn",panelClass:"accordion-content",elementClass:"accordion-item"});const p=document.querySelectorAll(".btn-svg-opn");p.forEach(t=>{t.addEventListener("click",()=>{p.forEach(s=>{s!==t&&s.classList.remove("rotate")}),t.classList.toggle("rotate")})});const m=document.querySelector(".js-reviews-box-list");v.defaults.baseURL="https://portfolio-js.b.goit.study/api";async function j(){try{return(await v.get("/reviews")).data}catch{g.error({message:"Error fetching reviews. Please try again later.",position:"topRight"});return}}async function P(){try{const t=await j();if(!t||t.length===0){m.innerHTML='<li class="reviews-list-card">Not Found</li>';return}const s=t.map(o=>`
          <li class="swiper-slide reviews-list-card">
            <img src="${o.avatar_url}" 
                 loading="lazy" 
                 alt="${o.author}" 
                 class="reviews-card-img" 
                 width="48" height="48">
            <div class="reviews-card-desc">
              <h3 class="reviews-card-subtitle">${o.author}</h3>
              <div class="reviews-card-text">${o.review}</div>
            </div>
          </li>
        `).join("");m.innerHTML=s}catch{g.error({message:"Error rendering reviews. Please try again later.",position:"topRight"})}}async function O(){await P(),new l(".reviews-swiper",{modules:[f,E],direction:"horizontal",slidesPerView:1,spaceBetween:16,navigation:{nextEl:".js-reviews-btn-next",prevEl:".js-reviews-btn-previous"},keyboard:{enabled:!0,onlyInViewport:!0},breakpoints:{320:{slidesPerView:1},768:{slidesPerView:2},1440:{slidesPerView:4}}})}O();const I=document.querySelector(".work-t-modal-container"),a=document.querySelector(".work-t-form"),d=document.querySelector(".work-t-modal-container"),V=document.querySelector(".work-t-input-email"),x=t=>{t.preventDefault();const s="https://portfolio-js.b.goit.study/api/requests";(e=>{const r={method:"post",body:JSON.stringify(e),headers:{"Content-Type":"application/json"}};return fetch(`${s}`,r).then(i=>{if(!i.ok)throw new Error(i.status);return i.json()})})({email:"client@gmail.com",comment:"comments"}).then(e=>{I.classList.add("js-is-open"),a.reset(),console.log(e)}).catch(e=>{V.classList.add("js-input-email"),alert("Invalid Email"),console.log(e)});const n={email:a.elements.user_email.value.trim(),comments:a.elements.user_comments.value.trim()};console.log(n)},B=t=>{d.classList.add("disabled")},M=t=>{d.classList.add("disabled")};a.addEventListener("submit",x);d.addEventListener("click",B);document.addEventListener("keydown",t=>{t.key==="Escape"&&M()});
//# sourceMappingURL=index.js.map
