import{A as d,S as a,N as u,a as f,E as g,b as p,K as b,i as w}from"./assets/vendor-PY9CkTNr.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const o of t.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&n(o)}).observe(document,{childList:!0,subtree:!0});function i(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=i(e);fetch(e.href,t)}})();const v=document.querySelector(".about-accordion-container");new d(v,{openOnInit:[0],showMultiple:!1,duration:500,elementClass:"about-ac",panelClass:"about-ac-panel",triggerClass:"about-ac-btn"});new a(".about-skills",{navigation:{nextEl:".about-swiper-btn"},keyboard:{enabled:!0,onlyInViewport:!0,pageUpDown:!0},mousewheel:{invert:!0},grabCursor:!0,touchEventsTarget:"wrapper",slideClass:"about-skills-item",slideActiveClass:"about-skills-item-accent",wrapperClass:"about-skills-list",slidesPerView:2,loopedSlides:2,spaceBetween:1,loop:!0,breakpoints:{768:{slidesPerView:3},1440:{slidesPerView:5,loopedSlides:5,spaceBetween:25}}});new a(".projects-swiper-container",{modules:[u,f,g],direction:"horizontal",loop:!1,slidesPerView:1,spaceBetween:10,mousewheel:!0,effect:"cards",grabCursor:!0,keyboard:{enabled:!0,onlyInViewport:!0},navigation:{nextEl:".projects-swiper-btn-next",prevEl:".projects-swiper-btn-prev",disabledClass:"projects-swiper-btn-disabled"}});document.querySelector(".accordion-container");new d(".accordion",{openOnInit:[],showMultiple:!1,duration:500,easing:"ease-in-out",triggerClass:"btn-svg-opn",panelClass:"accordion-content",elementClass:"accordion-item"});const l=document.querySelectorAll(".btn-svg-opn");l.forEach(r=>{r.addEventListener("click",()=>{l.forEach(s=>{s!==r&&s.classList.remove("rotate")}),r.classList.toggle("rotate")})});const c=document.querySelector(".js-reviews-box-list");p.defaults.baseURL="https://portfolio-js.b.goit.study/api";async function m(){try{return(await p.get("/reviews")).data}catch{w.error({message:"Error fetching reviews. Please try again later.",position:"topRight"});return}}async function h(){try{const r=await m();if(!r||r.length===0){c.innerHTML='<li class="reviews-list-card">Not Found</li>';return}const s=r.map(i=>`
          <li class="swiper-slide reviews-list-card">
            <img src="${i.avatar_url}" 
                 loading="lazy" 
                 alt="${i.author}" 
                 class="reviews-card-img" 
                 width="48" height="48">
            <div class="reviews-card-desc">
              <h3 class="reviews-card-subtitle">${i.author}</h3>
              <div class="reviews-card-text">${i.review}</div>
            </div>
          </li>
        `).join("");c.innerHTML=s}catch{w.error({message:"Error rendering reviews. Please try again later.",position:"topRight"})}}async function y(){await h(),new a(".reviews-swiper",{modules:[u,b],direction:"horizontal",slidesPerView:1,spaceBetween:16,navigation:{nextEl:".js-reviews-btn-next",prevEl:".js-reviews-btn-previous"},keyboard:{enabled:!0,onlyInViewport:!0},breakpoints:{320:{slidesPerView:1},768:{slidesPerView:2},1440:{slidesPerView:4}}})}y();
//# sourceMappingURL=index.js.map
